# Site settings
title: m4l1ce.me
email: jon@jonsomnia.com
description: > # this means to ignore newlines until "baseurl:"
    Stuff, things, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://m4l1ce.me" # the base hostname & protocol for your site
github_username:  m4l1c3

# Build settings
markdown: redcarpet
extensions: [fenced_code_blocks]

#collections/categories
collections:
    writeups:
        output: true
        permalink: /writeups/:name/
    bash:
        output: true
        permalink: /bash/:name/
    